# Generated by Django 5.1.3 on 2024-12-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_eid',
            field=models.BooleanField(default=False, verbose_name='Electrical and Instrument'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_pmd',
            field=models.BooleanField(default=False, verbose_name='Plant Maintenance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_qa',
            field=models.BooleanField(default=False, verbose_name='Quality Assurance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_uto',
            field=models.BooleanField(default=False, verbose_name='Utilities Operation'),
        ),
    ]
