# Generated by Django 5.1.3 on 2024-12-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_order',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='job_order',
            name='owner',
        ),
        migrations.AddField(
            model_name='job_order',
            name='lead_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipmentspecs',
            name='specs',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
