# Generated by Django 5.1.3 on 2024-12-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_order', '0002_alter_job_order_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_order',
            name='owner',
        ),
    ]
